### ISSUE TITLE
SignUp on demo is broken

### ISSUE THREAD

**Issue by adisos** [lynndylanhurley/j-toker#22]
Something wrong with backend. It shows 500 error on console

**Comment by hughkolias** [comment]
It's due to the switch to devise 4... whoever has access to the backend just has to change the strong_parameters from a proc (ie: 

`devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit( :username) })`

 to the new standard:

`devise_parameter_sanitizer.permit(:sign_up, keys: [:username])`

see: https://github.com/plataformatec/devise#strong-parameters

Hopefully this also helps anyone who is running into a similar issue.
